/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sbg' at '3/5/15 10:00 AM' with Gradle 2.2
 *
 * @author sbg, @date 3/5/15 10:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
